// import React from 'react'

// const App = () => {
//   return (
//     <>
//       <div className=' w-full h-screen bg-zinc-700'>
//           <h1>Rahul</h1>
//       </div>
//     </>
//   )
// }

// export default App


/**
 * This code was generated by Builder.io.
 */
import React from "react";
import MentoringApp from "./components/mentoring/MentoringApp";

const App = () => {
  return (
    <div>
      < MentoringApp />
      
    </div>
  );
};

export default App;
